Add default Spanish human time locale
pbrisbin/friendly-time pull request #14
Opened 2017-03-21 20:50 UTC by alx741

Not sure if adding default time locales for various languages is the right way to go, but the Yesod web framework seems to include them, and it's actually nice to have when i18n is required.

The idea is to include a couple of languages out of the box, if this PR is useful, other contributors may implement defaults for other languages as well hopefully.

If this is however not kind of stuff the package aims to provide, please feel free to dismiss this PR.

pd: I'm a native Spanish speaker so i'm sure this default makes sense (already tried it)

2017-07-11 14:13 UTC, pbrisbin commented
Sorry I missed this PR until now. I'm happy to accept it, once the build failure is sorted out. If you're able to look into it, that's great, otherwise I'll try to sort it out in the next week or two then just ask you to rebase before I merge.

2017-07-16 03:32 UTC, alx741 commented
mmm can't quite understand why it fails on `CABALVER=1.18`

2017-07-17 23:19 UTC, pbrisbin commented
I've updated this project with my usual setup now, which included moving to Circle CI. Please rebase on master and force-push. It should be green, then I'll merge and cut a new release. Thanks!

2017-07-17 23:47 UTC, pbrisbin commented on src/Data/Time/Format/Human.hs
> +spanishHumanTimeLocale = HumanTimeLocale
Just realized that without adding this to the exports, it's not doing much :)

WDYT of a new module, maybe `Data/Time/Format/Human.Locales` to hold this, and establish the pattern of adding more languages to that module?

2017-07-19 00:52 UTC, alx741 commented on src/Data/Time/Format/Human.hs
> +spanishHumanTimeLocale = HumanTimeLocale
That one is nice! let me try

2017-07-20 15:10 UTC, pbrisbin requested changes
I also just enabled building forks in Circle, so your next push should get a green status.

2017-07-20 15:10 UTC, pbrisbin commented on src/Data/Time/Format/Human.hs
> +
Can you revert the whitespace changes in this file?

2017-07-20 17:50 UTC, alx741 commented on src/Data/Time/Format/Human.hs
> +
Oh! my bad, fixing it

2017-07-20 20:39 UTC, pbrisbin commented on src/Data/Time/Format/Human.hs
> -
There still this and 1 other unexpected whitespace change here, can you remove them?

2017-07-21 17:19 UTC, pbrisbin approved these changes

2017-07-21 17:19 UTC, merged

2017-07-21 17:19 UTC, pbrisbin commented
Thanks!